blank_issues_enabled: false
contact_links:
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=MeowCodeOrg.meow-code&ssr=false#review-details
      about: Enjoying MeowCode? Leave a review here!
