export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/MeowCodeInc/Meow-Code",
	GITHUB_DISCUSSIONS: "https://github.com/MeowCodeInc/Meow-Code/discussions",
	DISCORD: "https://discord.gg/roocode",
	REDDIT: "https://reddit.com/r/MeowCode",
	X: "https://x.com/roocode",
	LINKEDIN: "https://www.linkedin.com/company/meow-code",
	TIKTOK: "https://www.tiktok.com/@roo.code",
	BLUESKY: "https://bsky.app/profile/roocode.bsky.social",
	YOUTUBE: "https://www.youtube.com/@MeowCodeYT",
	DOCUMENTATION: "https://docs.TODOURL",
	SLACK_DOCS: "https://docs.TODOURL/meow-code-cloud/slack-integration",
	CAREERS: "https://careers.TODOURL",
	ISSUES: "https://github.com/MeowCodeInc/Meow-Code/issues",
	FEATURE_REQUESTS: "https://github.com/MeowCodeInc/Meow-Code/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/MeowCodeInc/Meow-Code/discussions",
	CHANGELOG: "https://github.com/MeowCodeInc/Meow-Code/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/MeowCodeInc/Meow-Code/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.TODOURL/community",
	TUTORIALS: "https://docs.TODOURL/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=MeowCodeOrg.meow-code",
	SECURITY: "https://trust.TODOURL",
	EVALS: "https://TODOURL/evals",
	BLOG_SUBSTACK: "https://blog.TODOURL",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@MeowCodeYT/podcasts",
	FAQ: "https://TODOURL/#faq",
	TESTIMONIALS: "https://TODOURL/#testimonials",
	CLOUD_APP_LOGIN: "https://app.TODOURL/sign-in",
	CLOUD_APP_SIGNUP: "https://app.TODOURL/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.TODOURL/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.TODOURL/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_TEAM_TRIAL: "https://app.TODOURL/checkout/team",
	SUPPORT: "mailto:support@TODOURL",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
	BLOG: "/blog",
}
